# Generated by Django 5.2.13 on 2026-05-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kanji', models.CharField(max_length=200, null=True)),
                ('reading', models.CharField(max_length=200)),
                ('romaji', models.CharField(max_length=200)),
                ('meaning', models.CharField(max_length=200)),
                ('pos', models.CharField(max_length=50)),
            ],
        ),
    ]
