# Generated by Django 5.2.13 on 2026-05-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
