# Generated by Django 5.2.13 on 2026-05-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_flashcard_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='step',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
