# Generated by Django 5.2.13 on 2026-05-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_flashcard_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
